CREATE TABLE Loja_fisica (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    descricao VARCHAR(300),
    localizacao VARCHAR(100) NOT NULL,
    nome VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 